// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/24/2025, 9:46:42 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/plugins/**/*.{js,ts,mjs}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/composables/**/*.{js,ts,mjs}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/utils/**/*.{js,ts,mjs}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/xiaoshangfei/SourceCode/Personal/cattee-template/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;